name: Schedule Source Files Download
on:
  schedule:
    - cron: '36 6 * * *'
      timezone: "Europe/Sofia"
jobs: 
    update_lists:
      runs-on: ubuntu-latest
      steps:
        - name: Update source file 1
          run: curl -sSL "https://raw.githubusercontent.com/hagezi/dns-blocklists/main/wildcard/doh-vpn-proxy-bypass-onlydomains.txt" -o source_files/doh-vpn-proxy-bypass-onlydomains.txt
          shell: bash
          
        - name: Update source file 2
          run: curl -sSL "https://raw.githubusercontent.com/hagezi/dns-blocklists/main/wildcard/tif-onlydomains.txt" -o source_files/tif-onlydomains.txt
          shell: bash
          
        - name: Update source files 3
          run: curl -sSL "https://raw.githubusercontent.com/hagezi/dns-blocklists/main/wildcard/pro-onlydomains.txt" -o source_files/pro-onlydomains.txt
          shell: bash
