name: Schedule Source Files Download
on:
  workflow_dispatch:
  schedule:
    - cron: '50 0 * * *'
      timezone: "Europe/Sofia"

permissions:
  contents: write

jobs: 
    update_lists:
      runs-on: ubuntu-latest
      steps:
        - name: Check out repository
          uses: actions/checkout@v4

        - name: Update source file 1
          run: curl -sSL "https://cdn.jsdelivr.net/gh/hagezi/dns-blocklists@latest/wildcard/doh-vpn-proxy-bypass-onlydomains.txt" -o source_files/doh-vpn-proxy-bypass-onlydomains.txt
          
        - name: Update source file 2
          run: curl -sSL "https://cdn.jsdelivr.net/gh/hagezi/dns-blocklists@latest/wildcard/tif-onlydomains.txt" -o source_files/tif-onlydomains.txt
          
        - name: Update source files 3
          run: curl -sSL "https://cdn.jsdelivr.net/gh/hagezi/dns-blocklists@latest/wildcard/pro-onlydomains.txt" -o source_files/pro-onlydomains.txt
        - name: Commit & push changes (if any)
          run: |
            git config user.name "github-actions[bot]"
            git add source_files/*.txt
            if ! git diff --staged --quiet; then
            git commit -m "Update source_files from remote lists"
            git push
            else
            echo "No changes to commit"
            fi
